### ISSUE TITLE
Thanks! and 384.12?

### ISSUE THREAD

**Issue by maxbraketorque** [gzenux/asuswrt-rtn18u#6] opened 2019-07-18 01:28 UTC
This seems to be the only way to interact with the author.  I greatly appreciate you porting Merlin FW to RT-N18U, and I hope you continue to do it for a while.  Do you have an estimated date for porting over 384.12?

**Comment by gzenux** [comment] 2019-07-18 14:57
Thanks your affirmation.
Regarding to your question, actually the current stable release, which tag named rtn18u_384.11_1, has already merged Merlin 384.12.

The version naming has been diverged since rtn18u_384.10 (i.e. rtn18u_384.9 is the last synced version name). The main reason is the merging problem caused by incompatible prebuilt binary.

The next release is working in progress but I haven't pushed the updated code yet on github. (Normally I'll push the updated code after merging Merlin's stable/beta release)

The release date depends on official Merlin's release schedule and my progress of the code merging. I'll keep tracking for next Merlin release (384.13-mainline). That's all, thank you.

**Comment by maxbraketorque** [comment] 2019-07-18 23:44
Thanks much for the information about build numbers.  I will give 384.11_1 a try today.

**Comment by Eldenroot** [comment] 2019-07-19 18:04
Hi, first of all I am really impressed! Good job!

I have asked Merlin 2 times in past if he could support RT-N18u device but the answer was always same "NO". I fully understand, because it takes a lot of time and he does not own this device for testing.

Anyway now I see your project, I am a little bit confused.

Is it based on which fw? This one - https://github.com/RMerl/asuswrt-merlin.ng? So does it contain all features and additions from Merlin's fw?

What are the known issues?

**Comment by gzenux** [comment] 2019-07-22 04:40
The codebase is RT-N18U GPL release 3.0.0.4.382.18991 and the upstream codebase merged by this project is https://github.com/RMerl/asuswrt-merlin.ng (master or mainline branch).

Most of features and additions from Merlin's fw are included by this project, which are source available from Merlin's repository.

Some of feature enhancements or bug fixes are lacking since these features are not enabled by Asus and released as prebuilt binaries.

**Comment by Eldenroot** [comment] 2019-07-22 10:10
> Some of feature enhancements or bug fixes are lacking since these features are not enabled by Asus and released as prebuilt binaries.

Any list of features which are not included? Or some examples? Thx

**Comment by Eldenroot** [comment] 2019-07-22 10:13
Codebase - so it is not based on 3.0.0.4.382.51640???

**Comment by gzenux** [comment] 2019-07-22 13:11
> Any list of features which are not included? Or some examples? Thx

As I know, Adaptive QoS, AiProtection and AiMesh are not included by Asus on this model.

> Codebase - so it is not based on 3.0.0.4.382.51640??? I am a little bit confused, is that menas that it doeant not caontain new fixes etc from Asus newer fw versions?

I use 3.0.0.4.382.18991 as the initial codebase for this project but currently now it has merged Asus's 3.0.0.4.382.51634 changes and Merlin's 384.12 updates.
For more information, please refer to Changelog-RTN18U.txt (Changelog-NG.txt is updated by Merlin's project) in this project repository.

**Comment by Eldenroot** [comment] 2019-07-22 13:21
Ok, thank you. Now I understand, maybe would be nice to add it into your webpage - FAQs

So next release will contain fixes from 3.0.0.4.382.51640? 

Thank you, great fw, great work!

**Comment by Eldenroot** [comment] 2019-08-01 17:44
Just flashed the latest beta, everything seems to be fine! Thank you!

**Comment by pomidor11** [comment] 2019-08-02 16:41
Thank you! gzenux ;-)

**Closed** 2019-08-26 07:40 UTC
